### ISSUE TITLE
Create others search tasks 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-github#6]
Same design than : https://github.com/kestra-io/plugin-github/issues/5

but: 
- `io.kestra.plugin.github.code.Search`
- `io.kestra.plugin.github.commits.Search`
- `io.kestra.plugin.github.issues.Search`
- `io.kestra.plugin.github.topics.Search`
- `io.kestra.plugin.github.users.Search`

**Comment by loicmathieu** [comment]
Done in https://github.com/kestra-io/plugin-github/pull/7
